dr nic more echos

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
+set -e # fail fast
+set -o pipefail
+
 BUILD_DIR=$1
 CACHE_DIR=$2
 
@@ -35,20 +38,22 @@ if [ "$SCM_URL" != "" ]; then
   # if [[ "$SCM_URL" =~ \.(tgz|tar\.gz)$ ]]; then
   if [[ "$SCM_URL" =~ \.(tgz)$ ]]; then
     echo "=====> Downloading tgz archive: $SCM_URL"
-    curl -k -s "$SCM_URL" | tar xvz -C "$DIR"
+    curl -k -s "$SCM_URL" | tar xvz -C "$DIR" | indent
   elif [[ "$SCM_URL" =~ \.(zip)$ ]]; then
     echo "=====> Downloading zip archive: $SCM_URL"
     TEMPFILE=$(mktemp -t tempXXXXX)
-    curl -k -o "$TEMPFILE" "$SCM_URL"
-    unzip "$TEMPFILE" -d "$DIR"
+    curl -k -o "$TEMPFILE" "$SCM_URL" | indent
+    unzip "$TEMPFILE" -d "$DIR" | indent
     rm "$TEMPFILE"
   elif [[ "$SCM_URL" =~ \.(git)$ ]]; then
     if [[ -d $CACHE_DIR/.git ]]; then
+      echo "=====> Fetching existing repo"
       cd $CACHE_DIR/.git
-      git fetch origin
-      git checkout origin/$SCM_BRANCH
+      git fetch origin | indent
+      git checkout origin/$SCM_BRANCH | indent
     else
-      git clone $SCM_URL $CACHE_DIR
+      echo "=====> Cloning repo for the first time"
+      git clone $SCM_URL $CACHE_DIR | indent
     fi
   else
     echo "\$SCM_URL $SCM_URL was not detected as a tgz, zip or git"
@@ -56,10 +61,6 @@ if [ "$SCM_URL" != "" ]; then
   fi
 
   echo "=====> Download finished"
-
-  if [ "$SCM_BRANCH" != "" ]; then
-    git checkout $SCM_BRANCH
-  fi
 
   echo "=====> copying contents of $DIR to $1"
   cd $DIR
